@startuml
scale 800*800
skinparam dpi 200
skinparam classAttributeFontSize 8
skinparam classArrowFontSize 9
skinparam classFontSize 10
skinparam nodesep 120
skinparam ranksep 40
hide stereotype
skinparam class {
	BackgroundColor White
	BackgroundColor<<User>> LightBlue
	BackgroundColor<<Card>> LightYellow
}

class Card <<Card>> {
    Integer id
    List <int> [rows][columns]
    Integer price
}

class Invitation <<Invitation>> {
    Integer id
    Integer id_game
    Player from
    Player to
    Boolean isUnderWay
    Boolean isAccepted
    Boolean timeout
    String message
}

class Game <<Game>> {
    Integer id
    List <int> appearednumbers
    Float jackpot
    Player bingowinner
    Player linewinner
}
Card "has many" -left- "isplayed 1" Game

class User <<User>> {
    String username
    String email
    String password
    Boolean admin

}

class Player <<User>> extends User {
    Float wallet
    Game isPlaying_game
    Card isPlaying_card
}
Card "playedBy 1" -- "plays 1" Player
Game "plays in 1" -up- "has many" Player
Invitation "many" <-- "1" Player : invites
Invitation "1" <-- "1" Player : receives
Invitation "many" --> "1" Game : belongs


class Admin <<User>> extends User {

}
@enduml
